from typing import List, Dict, Any

MOCK_APPLICATIONS: List[Dict[str, Any]] = [
    {
        "id": 1,
        "name": "Valeria Morales",
        "email": "valeria.morales@example.com",
        "phone": "+1 (787) 555-0142",
        "location": "San Juan, PR",
        "modality": "Híbrido",
        "position": "Desarrollador Full Stack Senior",
        "department": "Ingeniería de Software",
        "experience_years": 6,
        "education": "Licenciatura en Ciencias de la Computación (UPR Río Piedras)",
        "english_level": "C1 - Avanzado Profesional",
        "salary_expectation": "$75,000 - $85,000 / año",
        "skills": ["Python", "FastAPI", "JavaScript", "PostgreSQL", "Docker", "React"],
        "certifications": ["AWS Certified Developer - Associate"],
        "previous_companies": ["FinTech Solutions PR", "Caribbean Cloud Tech"],
        "summary": "Desarrolladora Full Stack con 6 años construyendo APIs de alto rendimiento y arquitecturas de microservicios. Fuerte dominio de patrones de diseño limpios y pruebas automatizadas.",
        "applied_date": "2026-10-01",
        "status": "En Revisión"
    },
    {
        "id": 2,
        "name": "Carlos Méndez",
        "email": "carlos.mendez@example.com",
        "phone": "+1 (787) 555-0198",
        "location": "Ponce, PR",
        "modality": "Remoto",
        "position": "Ingeniero de Datos & Pipelines",
        "department": "Datos & Inteligencia de Negocios",
        "experience_years": 4,
        "education": "Ingeniería en Software (Politécnica de PR)",
        "english_level": "B2 - Intermedio Alto",
        "salary_expectation": "$65,000 - $75,000 / año",
        "skills": ["Python", "SQL", "Apache Airflow", "Pandas", "Snowflake", "dbt"],
        "certifications": ["Snowflake SnowPro Core", "dbt Fundamentals"],
        "previous_companies": ["DataVibe Analytics", "Banco Popular (Contratista)"],
        "summary": "Especialista en diseño y mantenimiento de pipelines de datos ETL/ELT. Experiencia migrando almacenes tradicionales a arquitecturas Cloud modernas.",
        "applied_date": "2026-10-02",
        "status": "Preseleccionado"
    },
    {
        "id": 3,
        "name": "Sofía Ramos",
        "email": "sofia.ramos@example.com",
        "phone": "+1 (787) 555-0321",
        "location": "Guaynabo, PR",
        "modality": "Presencial / Híbrido",
        "position": "Diseñadora UI/UX & Frontend Lead",
        "department": "Diseño & Producto",
        "experience_years": 7,
        "education": "Maestría en Interacción Humano-Computadora (Rochester Institute of Tech)",
        "english_level": "C2 - Bilingüe Nativo",
        "salary_expectation": "$80,000 - $90,000 / año",
        "skills": ["Figma", "Design Systems", "HTML5", "CSS3", "JavaScript", "WCAG 2.1"],
        "certifications": ["Nielsen Norman UX Master Certified"],
        "previous_companies": ["InnoDesign Studio", "HealthFirst Digital"],
        "summary": "Diseñadora líder con enfoque en accesibilidad web y sistemas de diseño escalables. Capaz de traducir requisitos de negocio complejos en experiencias intuitivas.",
        "applied_date": "2026-10-02",
        "status": "Entrevista Técnica"
    },
    {
        "id": 4,
        "name": "Diego Fernández",
        "email": "diego.fernandez@example.com",
        "phone": "+1 (787) 555-0455",
        "location": "Caguas, PR",
        "modality": "Remoto",
        "position": "Ingeniero Cloud & DevOps",
        "department": "Infraestructura & Operaciones",
        "experience_years": 5,
        "education": "Bachillerato en Ingeniería de Computadoras (UPR Mayagüez)",
        "english_level": "C1 - Avanzado",
        "salary_expectation": "$78,000 - $88,000 / año",
        "skills": ["Terraform", "Kubernetes", "Docker", "AWS", "CI/CD", "Linux", "Bash"],
        "certifications": ["AWS Solutions Architect Associate", "CKA (Kubernetes Administrator)"],
        "previous_companies": ["CloudSphere Technologies", "Aerospace Systems PR"],
        "summary": "Ingeniero DevOps con sólida experiencia en automatización de despliegues, seguridad perimetral y optimización de costes en la nube.",
        "applied_date": "2026-10-03",
        "status": "En Revisión"
    },
    {
        "id": 5,
        "name": "Elena Castillo",
        "email": "elena.castillo@example.com",
        "phone": "+1 (787) 555-0612",
        "location": "Mayagüez, PR",
        "modality": "Remoto",
        "position": "Científica de Datos & Machine Learning",
        "department": "Datos & Inteligencia de Negocios",
        "experience_years": 3,
        "education": "Maestría en Ciencias de Datos (UPR Mayagüez)",
        "english_level": "C1 - Avanzado",
        "salary_expectation": "$70,000 - $80,000 / año",
        "skills": ["Python", "Scikit-Learn", "PyTorch", "NLP", "FastAPI", "MLflow"],
        "certifications": ["TensorFlow Developer Certificate"],
        "previous_companies": ["AILabs Innovation", "Research Institute of PR"],
        "summary": "Investigadora y científica de datos enfocada en modelos predictivos, procesamiento de lenguaje natural (NLP) y despliegue de modelos en producción.",
        "applied_date": "2026-10-03",
        "status": "Preseleccionado"
    },
    {
        "id": 6,
        "name": "Alejandro Vega",
        "email": "alejandro.vega@example.com",
        "phone": "+1 (787) 555-0789",
        "location": "Bayamón, PR",
        "modality": "Presencial",
        "position": "Analista de Ciberseguridad & SOC",
        "department": "Seguridad de la Información",
        "experience_years": 4,
        "education": "Bachillerato en Redes y Ciberseguridad (Univ. Interamericana)",
        "english_level": "B2 - Intermedio Alto",
        "salary_expectation": "$62,000 - $72,000 / año",
        "skills": ["SIEM", "Splunk", "Wireshark", "Hardening Linux/Windows", "ISO 27001", "Python"],
        "certifications": ["CompTIA Security+", "CompTIA CySA+"],
        "previous_companies": ["SecureNet Defense", "Hospitality Services PR"],
        "summary": "Analista de seguridad enfocado en detección y respuesta ante incidentes, análisis de vulnerabilidades y cumplimiento normativo.",
        "applied_date": "2026-10-04",
        "status": "En Revisión"
    },
    {
        "id": 7,
        "name": "Camila Ortiz",
        "email": "camila.ortiz@example.com",
        "phone": "+1 (787) 555-0834",
        "location": "San Juan, PR",
        "modality": "Híbrido",
        "position": "Product Owner / Gestora de Producto",
        "department": "Diseño & Producto",
        "experience_years": 8,
        "education": "Licenciatura en Administración de Empresas y Sistemas de Información",
        "english_level": "C2 - Bilingüe",
        "salary_expectation": "$85,000 - $95,000 / año",
        "skills": ["Scrum", "Jira", "Product Roadmap", "Análisis de Métricas", "User Stories", "SQL"],
        "certifications": ["PSPO I (Professional Scrum Product Owner)", "PMP"],
        "previous_companies": ["Telecomm PR", "E-Commerce Global"],
        "summary": "Líder de producto orientada a resultados con trayectoria coordinando equipos multidisciplinarios de ingeniería y diseño para el lanzamiento de aplicaciones SaaS.",
        "applied_date": "2026-10-04",
        "status": "Entrevista Técnica"
    },
    {
        "id": 8,
        "name": "Gabriel Navarro",
        "email": "gabriel.navarro@example.com",
        "phone": "+1 (787) 555-0941",
        "location": "Humacao, PR",
        "modality": "Remoto",
        "position": "Ingeniero de Automatización de Pruebas (QA)",
        "department": "Ingeniería de Software",
        "experience_years": 3,
        "education": "Grado Asociado en Ciencias Computacionales",
        "english_level": "B2 - Intermedio",
        "salary_expectation": "$55,000 - $65,000 / año",
        "skills": ["Selenium", "Playwright", "Python", "Pytest", "Postman", "Git"],
        "certifications": ["ISTQB Foundation Level"],
        "previous_companies": ["QualitySoft QA", "Island Retail App"],
        "summary": "Ingeniero QA centrado en automatización de pruebas end-to-end, testing de APIs REST y validación de regresión en entornos de integración continua.",
        "applied_date": "2026-10-05",
        "status": "En Revisión"
    },
    {
        "id": 9,
        "name": "Mariana Nieves",
        "email": "mariana.nieves@example.com",
        "phone": "+1 (787) 555-1022",
        "location": "Dorado, PR",
        "modality": "Híbrido",
        "position": "Desarrolladora Mobile (iOS / Flutter)",
        "department": "Ingeniería de Software",
        "experience_years": 5,
        "education": "Bachillerato en Ingeniería de Software (Politécnica de PR)",
        "english_level": "C1 - Avanzado",
        "salary_expectation": "$72,000 - $82,000 / año",
        "skills": ["Flutter", "Dart", "Swift", "iOS", "Firebase", "REST APIs", "State Management"],
        "certifications": ["Google Associate Android Developer"],
        "previous_companies": ["AppWave Studios", "MobileFin Technologies"],
        "summary": "Desarrolladora de aplicaciones móviles con más de 10 apps publicadas en App Store y Google Play. Especializada en interfaces fluidas y rendimiento offline-first.",
        "applied_date": "2026-10-05",
        "status": "Preseleccionado"
    },
    {
        "id": 10,
        "name": "Héctor Santana",
        "email": "hector.santana@example.com",
        "phone": "+1 (787) 555-1150",
        "location": "Arecibo, PR",
        "modality": "Remoto",
        "position": "Arquitecto Backend & Microservicios",
        "department": "Ingeniería de Software",
        "experience_years": 9,
        "education": "Bachillerato y Maestría en Ciencias de la Computación (UPR)",
        "english_level": "C1 - Avanzado Profesional",
        "salary_expectation": "$95,000 - $110,000 / año",
        "skills": ["Python", "Go", "Kafka", "Redis", "PostgreSQL", "gRPC", "Arquitectura Hexagonal"],
        "certifications": ["AWS Certified Solutions Architect - Professional"],
        "previous_companies": ["Global Payment Grid", "Enterprise Cloud Logistics"],
        "summary": "Arquitecto de software especializado en sistemas distribuidos de alta concurrencia, mensajería asíncrona con Kafka y diseño de bases de datos escalables.",
        "applied_date": "2026-10-06",
        "status": "Entrevista Técnica"
    }
]
